### ISSUE TITLE
Stabled pets interface minor aggravations

### ISSUE THREAD

**Issue by nancikennedy** [Trodrigs1120/WoWHunterPetsAddonFork#6]
The stabled pets window is always open when I log into my hunters, and cannot be closed via escape (like normal blizzard frames can be). It also defaults to no selection. So, requesting 3 things...

1) Be able to turn off it's ability to open at log in.
2) Add the ability to close the window via the escape key.
3) Make the currently logged in character the default selection, or enable profiles.

**Comment by Trodrigs1120** [comment]
Acknowledged, I'm trying to do some updating to the pet database right now since its missing the feathermane family entirely. It's on the to do list.

**Comment by nancikennedy** [comment]
Cool!

**Comment by Trodrigs1120** [comment]
The stables window no longer auto pops up when you log into a character. It will also automatically open to the stables of the character you are logged into, and of course the escape key works as well now :)

I just pushed the latest version to curse and it should get approved in about 10 or so minutes.
